markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: "潇湘雨"
markdown: rdiscount

author: "jiangyewen"
atom-baseurl: "http://jiangyewen.github.com"
disqus: "none"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

